### ISSUE TITLE
Governor made the CPU stucked at 1020 when a freq changed on some games

### ISSUE THREAD

**Issue by timunkun** [hanai3Bi/Switch-OC-Suite#1]
Here's the video 
https://drive.google.com/file/d/1zk89g2wYrSqu_r00Mn9epAwCQXnZImJf/view?usp=drivesdk

Only tested with Xenoblade Chronicles 3. The older repo (27th jan) runs without problem. But it's broken starting at 3rd feb commit.

**Comment by hanai3Bi** [comment]
I've analyzed the code, but haven't figured out what exactly is causing the problem.
For Xenoblade Chronicles 3, if CPU governor is enabled, the clock is stuck at 1020, or if set correctly, roll back to 1020 on RefreshContext()
My guess is that either race condition, or the game's perf_conf settings are causing problems. (The game seems to utilize only Core #0, so Core#0 load is like 100% but Core #1 and #2 are about 10%)

I will continue to investigate, but meanwhile it shouldn't be a problem since the clock is set correctly during in-game play.

**Comment by timunkun** [comment]
Thank you for reaching this issue. About disabling the governor. Kazu's suite always had like a weird voltage inconsistency on CPU side. For the example, if i higher the clockspeed to 2091mhz above, the voltage will stucked at 870mV after i went to homescreen. Governor is the only workaround for this problem since it will made the voltage increase properly. Maybe you can look around with this. And probably the problem is on the kips itself since it's not really a problem when i use cooler's old kip back then (mid 2022).
