### ISSUE TITLE
Add functionality for frequency governor

### ISSUE THREAD

**Issue by YCH01001** [hanai3Bi/Switch-OC-Suite#28]
Add functionality for frequency governor
On - Off - Handheld Only

Handheld can bring good battery life to SWITCH, but don’t worry about it in Docked, it’s very troublesome to switch every time

**Comment by hanai3Bi** [comment]
okay will make it configurable in sys-clk ini file

**Comment by monstrosities** [comment]
Thanks for looking at this option, I asked about exactly the same thing a while ago on the older project.

Since you are looking at this what do you think about also adding an option to make the governor opt-in on a per game basis instead of opt-out? Or maybe removing the global option for governor and allowing the user to set it per game would be better? 

I don't know how most people use it but personally I have found that I use the governor with a few games in handheld mode but not for most of them and not at all in docked mode, so that means after turning the global miscellaneous option on to enable the governor I then have to disable it for many games and every new game using the individual app profile for CPU/GPU governors. It ends up being a lot of management because of the way the option is structured.

**Comment by hanai3Bi** [comment]
Feature implemented. will be included in next version.

I think current setting of enabling governor for all titles when governor is enabled is fine, because i think it's rare that someone would want to use governor only on very specific titles and not use for rest

**Comment by hanai3Bi** [comment]
closed as new version came out
